services:
  mariadb:
    image: mariadb:11.4
    container_name: mingling-db
    ports:
      - "${DB_PORT}:3306"
    environment:
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      TZ: Asia/Seoul
    volumes:
      - mariadb-data:/var/lib/mysql
#      - ./init-db:/docker-entrypoint-initdb.d
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost", "-u", "root", "-p${DB_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - mingling-network

  redis:
    image: redis:7.2
    container_name: mingling-redis
    ports:
      - "${REDIS_PORT}:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - mingling-network

volumes:
  mariadb-data:
    driver: local
  redis-data:
    driver: local

networks:
  mingling-network:
    driver: bridge